apiVersion: apps/v1
kind: Deployment
metadata:
  name: collections
  labels:
    app: collections
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collections
  template:
    metadata:
      labels:
        app: collections
    spec:
      containers:
      - name: collections
        image: eu.gcr.io/grid-301122/collections:0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: gu-config
          mountPath: /etc/gu
        - name: grid-config
          mountPath: /etc/grid
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: grid-aws-access-token
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: grid-aws-access-token
              key: AWS_SECRET_ACCESS_KEY
        - name: PLAY_SECRET
          valueFrom:
            secretKeyRef:
              name: grid-play-secret
              key: play-secret
        resources:
          limits:
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /management/healthcheck
            port: 9000
      volumes:
      - name: gu-config
        configMap:
          name: gu
      - name: common-config
        configMap:
          name: common
      - name: grid-config
        configMap:
          name: grid

