apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgops
  labels:
    app: imgops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imgops
  template:
    metadata:
      labels:
        app: imgops
    spec:
      containers:
      - name: imgops
        image: eu.gcr.io/grid-301122/imgops:0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: imgops
          subPath: nginx.conf
          mountPath: /etc/nginx/nginx.conf
      volumes:
      - name: imgops
        configMap:
          name: imgops
