apiVersion: apps/v1
kind: Deployment
metadata:
  name: kahuna
  labels:
    app: kahuna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kahuna
  template:
    metadata:
      labels:
        app: kahuna
    spec:
      containers:
      - name: kahuna
        image: eu.gcr.io/grid-301122/kahuna:0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: gu-config
          mountPath: /etc/gu
        - name: grid-config
          mountPath: /etc/grid
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "384Mi"
        env:
        - name: PLAY_SECRET
          valueFrom:
            secretKeyRef:
              name: grid-play-secret
              key: play-secret
        livenessProbe:
          initialDelaySeconds: 120
          httpGet:
            path: /management/healthcheck
            port: 9000
        readinessProbe:
          httpGet:
            path: /management/healthcheck
            port: 9000
      volumes:
      - name: gu-config
        configMap:
          name: gu
      - name: common-config
        configMap:
          name: common
      - name: grid-config
        configMap:
          name: grid
