apiVersion: apps/v1
kind: Deployment
metadata:
  name: usage
  labels:
    app: usage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usage
  template:
    metadata:
      labels:
        app: usage
    spec:
      containers:
      - name: usage
        image: eu.gcr.io/grid-301122/usage:containerised
        imagePullPolicy: Always
        volumeMounts:
        - name: gu-config
          mountPath: /etc/gu
        - name: grid-config
          mountPath: /etc/grid
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: grid-aws-access-token
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: grid-aws-access-token
              key: AWS_SECRET_ACCESS_KEY
        - name: PLAY_SECRET
          valueFrom:
            secretKeyRef:
              name: grid-play-secret
              key: play-secret
        livenessProbe:
          initialDelaySeconds: 120
          httpGet:
            path: /management/healthcheck
            port: 9000
        readinessProbe:
          httpGet:
            path: /management/healthcheck
            port: 9000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "384Mi"
      volumes:
      - name: gu-config
        configMap:
          name: gu
      - name: grid-config
        configMap:
          name: grid
