apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: media-api-lb-healthcheck
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /management/healthcheck
  targetRef:
    group: ""
    kind: Service
    name: media-api
